openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /projects:
    $ref: "./paths/projects.yaml"
  /users:
    $ref: "./paths/users.yaml"
components:
  schemas:
    Project:
      $ref: "./schemas/Project.yaml"
    User:
      $ref: "./schemas/User.yaml"
