type: object
properties:
  id:
    type: string
  name:
    type: string
  description:
    type: string
  status:
    type: string
    enum:
      - active
      - inactive
required:
  - name
  - status
